# Manipulación de datos con Numpy

In [3]:
# importación de librería

import numpy as np


In [7]:
# creación de un array

lista = [1,2,3,4,5,6,7,8,9]

arr = np.array(lista)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
type(arr)

numpy.ndarray

In [11]:
# Creación de varios arrays
matriz = [[1,2,3],[7,8,9],[12,13,14]]
matriz = np.array(matriz)
matriz

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [12, 13, 14]])

In [18]:
# Indexado
# Unidimensional
print(arr[0])
# Multidimensional
print(matriz[0])
# Multidimensional
print(matriz[0,0])
print(matriz[0,2])
print(matriz[2,0])


1
[1 2 3]
1
3
12


In [25]:
# Acceso a multiples objetos
# Slicing
# Unidimensional
print(arr[0:3]) #esto es lo mismo que..
print(arr[:3]) #esto
print(matriz[0:2])
print(matriz[:2])


[1 2 3]
[1 2 3]
[[1 2 3]
 [7 8 9]]
[[1 2 3]
 [7 8 9]]


In [29]:
# Lo siguiente imprime todo
print(matriz[::])
print(arr[3:])

[[ 1  2  3]
 [ 7  8  9]
 [12 13 14]]
[4 5 6 7 8 9]


In [33]:
# Manejo de multidimensionalidad con el slicing

print(matriz[1:,1:2])
print(matriz[1:,1:])

[[ 8]
 [13]]
[[ 8  9]
 [13 14]]
